[project]
name = "dsml"
version = "0.1.0"
description = "A data science & machine learning project"
requires-python = ">=3.9"

dependencies = [
  "pandas",
  "numpy",
  "scipy",
  "scikit-learn",
  "matplotlib",
  "seaborn"
]
